/* Copyright 2020 QMK
 *
 * This file was auto-generated by:
 *    `qmk chibios-confmigrate -i keyboards/handwired/68keys/halconf.h -r platforms/chibios/common/configs/halconf.h`
 */

#pragma once

#define HAL_USE_I2C FALSE

#include_next <halconf.h>
