#pragma once

/* Default to a very simple RGB effect */
#undef RGB_MATRIX_STARTUP_MODE
#undef RGB_MATRIX_STARTUP_HUE
#undef RGB_MATRIX_STARTUP_SAT
#undef RGB_MATRIX_STARTUP_VAL

#define RGB_MATRIX_STARTUP_MODE RGB_MATRIX_SOLID_REACTIVE_SIMPLE
#define RGB_MATRIX_STARTUP_HUE 0
#define RGB_MATRIX_STARTUP_SAT 255
#define RGB_MATRIX_STARTUP_VAL RGB_MATRIX_MAXIMUM_BRIGHTNESS

/* In order to enable CMD-OPT-ESC, when I'm use KC_GESC */
#define GRAVE_ESC_GUI_OVERRIDE
